import { Toaster } from '@/components/ui/toaster';
import type { Metadata, Viewport } from 'next';
// import localFont from 'next/font/local';
import { Poppins } from 'next/font/google';

import QueryProvider from '@/lib/query-provider';
import Image from 'next/image';
import '../globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Job Hunt',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
};

export default function AuthRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative overflow-x-hidden`}>
        <QueryProvider>
          <main className="grid grid-cols-2">
            <div className="relative h-screen">
              <div className="absolute w-full h-full">
                <Image
                  src={'/images/bg-auth.png'}
                  alt="image"
                  fill
                  objectPosition="top"
                />
              </div>
            </div>

            <div className="w-full relative">
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
                {children}
              </div>
            </div>
          </main>

          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
