import CNavbar from '@/components/layouts/CNavbar';
import CFooter from '@/components/organism/CFooter';
import { Toaster } from '@/components/ui/toaster';
import AuthProvider from '@/providers/AuthProvider';
import type { Metadata, Viewport } from 'next';
import '../globals.css';

import QueryProvider from '@/lib/query-provider';
import { Poppins } from 'next/font/google';
import Image from 'next/image';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Job Hunt',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} relative overflow-x-hidden bg-gray-50`}
      >
        <div>
          <Image src="/images/download.png" alt="images" fill />
        </div>

        <QueryProvider>
          <AuthProvider>
            <CNavbar />

            <main className="relative">{children}</main>

            <CFooter />

            <Toaster />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
