import CNavbar from '@/components/layouts/CNavbar';
import QueryProvider from '@/lib/query-provider';
import AuthProvider from '@/providers/AuthProvider';
import { Metadata, Viewport } from 'next';
import { Poppins } from 'next/font/google';
import React from 'react';
import '../globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Job Hunt',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
};

export default function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative overflow-x-hidden`}>
        <QueryProvider>
          <AuthProvider>
            <CNavbar />
            <main className="px-32">{children}</main>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
